### ISSUE TITLE
Pkcs1 support, or any other padding

### ISSUE THREAD

**Issue by qstyler** [tugrul/node-mcrypt#12]
Hi! Does your module have any sort of padding support?
Or should I pad  the message by myself?

**Comment by scalabl3** [comment]
or removing padding during decrypt, like PKCS#5 :)

**Comment by Dexus** [comment]
:+1:

**Comment by tugrul** [comment]
This feature is implemented in new library named [cryptian](https://github.com/tugrul/cryptian)
