### ISSUE TITLE
Having an issue with blowfish encryption in 0.0.9 (0.0.7 worked)

### ISSUE THREAD

**Issue by drewlesueur** [tugrul/node-mcrypt#14]
Thanks for this library. This may be user error -- in version 0.0.7 this worked, and in 0.0.9 this doesn't

    var MCrypt = require('mcrypt').MCrypt;
    var m = new MCrypt('blowfish', 'nofb')
    m.validateKeySize(false)
    m.open('FooBar', '12345678')
    var t = m.encrypt('some random text')
    var b = t.toString('base64')
    console.log(b)

In v0.0.7 I get `R95YegoSAtz/LqPs16zkPw==`

In v0.0.9 I get `c29tZSByYW5kb20gdGV4dA==` which is just base64 of the original text.

**Comment by tugrul** [comment]
Thank you. I fixed and published to npm as 0.0.10
