### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by AntSworD** [tugrul/node-mcrypt#18]
CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:10:20: warning: mcrypt.h: No such file or directory
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:27: error: expected '>' before '(' token
../src/mcrypt.h:57: error: 'MCRYPT' does not name a type
../src/mcrypt.cc: In constructor 'MCrypt::MCrypt(const v8::Arguments&)':
../src/mcrypt.cc:17: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:17: error: 'mcrypt_module_open' was not declared in this scope
../src/mcrypt.cc: In destructor 'virtual MCrypt::~MCrypt()':
../src/mcrypt.cc:21: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:21: error: 'mcrypt_module_close' was not declared in this scope
../src/mcrypt.cc: At global scope:
../src/mcrypt.cc:25: error: expected '>' before '(' token
../src/mcrypt.cc: In member function 'char* MCrypt::transform(const char*, size_t*, int*)':
../src/mcrypt.cc:32: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:32: error: there are no arguments to 'mcrypt_enc_is_block_algorithm' that depend on a template parameter, so a declaration of 'mcrypt_enc_is_block_algorithm' must be available
../src/mcrypt.cc:32: error: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../src/mcrypt.cc:33: error: there are no arguments to 'mcrypt_enc_get_block_size' that depend on a template parameter, so a declaration of 'mcrypt_enc_get_block_size' must be available
../src/mcrypt.cc:49: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:53: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:53: error: 'modify' cannot be used as a function
../src/mcrypt.cc:57: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:57: error: there are no arguments to 'mcrypt_generic_deinit' that depend on a template parameter, so a declaration of 'mcrypt_generic_deinit' must be available
../src/mcrypt.cc: In member function 'std::vector<long unsigned int, std::allocator<long unsigned int> > MCrypt::getKeySizes()':
../src/mcrypt.cc:65: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:65: error: 'mcrypt_enc_get_supported_key_sizes' was not declared in this scope
../src/mcrypt.cc:68: error: 'mcrypt_free' was not declared in this scope
../src/mcrypt.cc:70: error: 'mcrypt_enc_get_key_size' was not declared in this scope
../src/mcrypt.cc:88: error: 'mcrypt_free' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::New(const v8::Arguments&)':
../src/mcrypt.cc:108: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:108: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::Open(const v8::Arguments&)':
../src/mcrypt.cc:124: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:124: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:195: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:195: error: 'mcrypt_enc_get_iv_size' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::Encrypt(const v8::Arguments&)':
../src/mcrypt.cc:212: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:212: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:222: error: 'mcrypt_generic' was not declared in this scope
../src/mcrypt.cc:222: error: no matching function for call to 'MCrypt::transform(char*, size_t*, int*)'
../src/mcrypt.cc:227: error: 'mcrypt_generic' was not declared in this scope
../src/mcrypt.cc:227: error: no matching function for call to 'MCrypt::transform(char*, size_t*, int*)'
../src/mcrypt.cc:234: error: 'mcrypt_strerror' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::Decrypt(const v8::Arguments&)':
../src/mcrypt.cc:254: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:254: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:264: error: 'mdecrypt_generic' was not declared in this scope
../src/mcrypt.cc:264: error: no matching function for call to 'MCrypt::transform(char*, size_t*, int*)'
../src/mcrypt.cc:268: error: 'mdecrypt_generic' was not declared in this scope
../src/mcrypt.cc:268: error: no matching function for call to 'MCrypt::transform(char*, size_t*, int*)'
../src/mcrypt.cc:275: error: 'mcrypt_strerror' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::SelfTest(const v8::Arguments&)':
../src/mcrypt.cc:319: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:319: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:321: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:321: error: 'mcrypt_enc_self_test' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::IsBlockAlgorithmMode(const v8::Arguments&)':
../src/mcrypt.cc:333: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:333: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:335: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:335: error: 'mcrypt_enc_is_block_algorithm_mode' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::IsBlockAlgorithm(const v8::Arguments&)':
../src/mcrypt.cc:347: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:347: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:349: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:349: error: 'mcrypt_enc_is_block_algorithm' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::IsBlockMode(const v8::Arguments&)':
../src/mcrypt.cc:361: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:361: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:363: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:363: error: 'mcrypt_enc_is_block_mode' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GetBlockSize(const v8::Arguments&)':
../src/mcrypt.cc:375: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:375: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:377: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:377: error: 'mcrypt_enc_get_block_size' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GetKeySize(const v8::Arguments&)':
../src/mcrypt.cc:387: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:387: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:389: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:389: error: 'mcrypt_enc_get_key_size' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GetSupportedKeySizes(const v8::Arguments&)':
../src/mcrypt.cc:399: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:399: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GetIvSize(const v8::Arguments&)':
../src/mcrypt.cc:417: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:417: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:419: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:419: error: 'mcrypt_enc_get_iv_size' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::HasIv(const v8::Arguments&)':
../src/mcrypt.cc:429: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:429: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:431: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:431: error: 'mcrypt_enc_mode_has_iv' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GetAlgorithmName(const v8::Arguments&)':
../src/mcrypt.cc:443: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:443: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:445: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:445: error: 'mcrypt_enc_get_algorithms_name' was not declared in this scope
../src/mcrypt.cc:447: error: 'mcrypt_free' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GetModeName(const v8::Arguments&)':
../src/mcrypt.cc:457: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:457: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:459: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:459: error: 'mcrypt_enc_get_modes_name' was not declared in this scope
../src/mcrypt.cc:461: error: 'mcrypt_free' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GenerateIv(const v8::Arguments&)':
../src/mcrypt.cc:471: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:471: error: 'MCRYPT_FAILED' was not declared in this scope
../src/mcrypt.cc:473: error: 'class MCrypt' has no member named 'mcrypt_'
../src/mcrypt.cc:473: error: 'mcrypt_enc_get_iv_size' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GetAlgorithmNames(const v8::Arguments&)':
../src/mcrypt.cc:492: error: 'mcrypt_list_algorithms' was not declared in this scope
../src/mcrypt.cc:504: error: 'mcrypt_free_p' was not declared in this scope
../src/mcrypt.cc: In static member function 'static v8::Handle<v8::Value> MCrypt::GetModeNames(const v8::Arguments&)':
../src/mcrypt.cc:515: error: 'mcrypt_list_modes' was not declared in this scope
../src/mcrypt.cc:526: error: 'mcrypt_free_p' was not declared in this scope
gmake: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1

**Comment by tugrul** [comment]
```
../src/mcrypt.h:10:20: warning: mcrypt.h: No such file or directory
```
Looks like libmcrypt and header files not installed or header not in the include path. 

You can modify include_path if libmcrypt installed and you know where the header file.

**Comment by AntSworD** [comment]
thx！i am sorry. I found the server machine of my company has some problems …
