### ISSUE TITLE
how can I  convert des/ecb/nopadding written java into node  use mcrypt

### ISSUE THREAD

**Issue by zaczhou** [tugrul/node-mcrypt#28]
This is my ex:

var MCrypt = require('mcrypt').MCrypt;
var desEcb = new MCrypt('des', 'ecb');
desEcb.open('aa0de112'); // we are set the key
var ciphertext = desEcb.encrypt('62120907316962');
console.log(ciphertext.toString('base64')); 

the result is +6QVWOfvKe1pzz6sFaZxPQ==

but in java  i got  +6QVWOfvKe3ZIf8QC7jklg==  

can you help me fix  this problom?  

thanks a lot

**Comment by tugrul** [comment]
So PHP evaluated same result:

```php
echo base64_encode(mcrypt_encrypt('des', 'aa0de112', '62120907316962', 'ecb'));
```

output:
```
+6QVWOfvKe1pzz6sFaZxPQ==
```
