### ISSUE TITLE
Can't install on iojs v3.2.0

### ISSUE THREAD

**Issue by matylla** [tugrul/node-mcrypt#31]
I know the issue has been addressed in #29 but a proper fix for this is still needed.

````
$ iojs -v
v3.2.0
````

````
$ npm install mcrypt --save

> mcrypt@0.1.2 install /Users/matylla/Kraken/web-interface/node_modules/mcrypt
> node-gyp rebuild --release

  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o
In file included from ../lib/libmcrypt/modules/algorithms/3-way.c:14:
../lib/libmcrypt/lib/libdefs.h:55:11: fatal error: 'endian.h' file not found
# include <endian.h>
          ^
1 error generated.
make: *** [Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o] Error 1
````

**Comment by alanshaw** [comment]
Same here :(

**Comment by pmaganti** [comment]
I am getting the same error.

`npm install mcrypt -g
\
> mcrypt@0.1.2 install /usr/local/lib/node_modules/mcrypt
> node-gyp rebuild --release

  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o
In file included from ../lib/libmcrypt/modules/algorithms/3-way.c:14:
../lib/libmcrypt/lib/libdefs.h:55:11: fatal error: 'endian.h' file not found
# include <endian.h>
          ^
1 error generated.
make: *** [Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/local/lib/node_modules/mcrypt
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "mcrypt" "-g"
npm ERR! node v0.10.28
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.2 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.1.2 install script 'node-gyp rebuild --release'.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

> mcrypt@0.1.2 preuninstall /usr/local/lib/node_modules/mcrypt
> rm -rf build/*`

**Comment by tugrul** [comment]
Please use mcrypt@0.0.15 version. I'm working on libmcrypt source to port cpp.

**Comment by gsklee** [comment]
Used 0.0.15 and still get a lot of errors:

```
In file included from ../src/mcrypt.cc:3:
In file included from ../src/mcrypt.h:9:
../node_modules/nan/nan.h:324:27: error: redefinition of
      'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/kaylee/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate
      function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
```

**Comment by erickhun** [comment]
same for me latest version or 0.0.15

**Comment by royreiss** [comment]
Same here using node 4.0

**Comment by malhayek2014** [comment]
I get this error when I try to install it on Windows. I am using Node.js 4


C:\Program Files\nodejs\node_modules\mcrypt>if not defined npm_config_node_gyp (
node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
les\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release
 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\mcrypt
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "mcrypt"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.3 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mcrypt@0.1.3 install script 'node-gyp rebuild --release'.

npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

**Comment by FlorianBezagu** [comment]
:+1: 

Same errors here

**Comment by Duncan00** [comment]
Same here

**Comment by Duncan00** [comment]
node v4.2.1
node-gyp v3.0.3
nan v2.1.0

```
npm install --save mcrypt@0.0.15
```
same error as @gsklee

**Comment by jsolis** [comment]
+1

node -v v4.2.1
node-gyp -v v3.0.3
mcrypt 0.0.15

**Comment by tugrul** [comment]
I should update convention to fix but looks like bigger differences by node v4. I'm too busy and i can't allocate time for this job.

**Comment by tugrul** [comment]
I published npm release for this issue

**Comment by jsolis** [comment]
First off, thanks for the release.  I do have a question though.  Because our devs use Macs, we've been using that `0.0.15` version.  Do you think there is any chance that these changes could be applied to a branch of `0.0.15`?  I'm unfamiliar with C and unfamiliar with why the later releases don't work on a mac, so please forgive me if my question is misguided.

**Comment by silversoup** [comment]
Having problem installing both 0.0.15 and 0.1.5 on mac 10.10.5 (node 4.2.2, node-gyp 3.0.3). I brew installed libmcrypt, but wasn't able to find libmcrypt-dev.

**Comment by jsolis** [comment]
FYI the 0.1.x version don't work on a mac (the reason why is documented in other issues). 

The 0.0.15 version works on Mac but doesn't work with node v. 4.2.x. That's what this issue is all about.

**Comment by tugrul** [comment]
@silversoup  @jsolis can you share npm log for mac?

**Comment by royreiss** [comment]
Thanks for the commit guys!  Just installed with Node 5.0 and it seems to be working great.

**Comment by jsolis** [comment]
Pasted the npm-debug.log to a gist using node 0.12.7 on a mac.  Let me know if you need anything else.

https://gist.github.com/jsolis/836d465aedf649930a21

**Comment by tugrul** [comment]
I published `mcrypt@0.1.6`

**Comment by jsolis** [comment]
Thanks for the quick update.  I just tried installing it, but unfortunately got the following error

```
> mcrypt@0.1.6 install /Users/jsolis/Sites/pcln-request-handler/node_modules/mcrypt
> node-gyp rebuild --release

  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o
In file included from ../lib/libmcrypt/modules/algorithms/3-way.c:14:
../lib/libmcrypt/lib/libdefs.h:45:11: fatal error: 'endian.h' file not found
# include <endian.h>
          ^
1 error generated.
make: *** [Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/jsolis/Sites/pcln-request-handler/node_modules/mcrypt
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPACKAGEJSON pcln-request-handler@1.0.10 No repository field.
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.6 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.1.6 install script 'node-gyp rebuild --release'.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jsolis/Sites/pcln-request-handler/npm-debug.log

```

**Comment by tugrul** [comment]
@jsolis http://stackoverflow.com/questions/20813028/endian-h-not-found-on-mac-osx

**Comment by jsolis** [comment]
Thanks for the reference.  I had xcode CLI installed and updated already, but the suggestion to copy `endian.h` from `/usr/include/machine` to `/usr/include` got me past that error, but then got the below error.  I don't have `byteswap.h` anywhere on my machine.  I searched around on google for a little and found a few references, but all of them seemed to involve a code fix like this one:
https://github.com/ferol/Lunchbox/commit/ae333fccd621778d88aced9533a135a25316cef1

¯\_(ツ)_/¯

```
> mcrypt@0.1.6 install /Users/jsolis/Sites/pcln-request-handler/node_modules/mcrypt
> node-gyp rebuild --release

  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o
In file included from ../lib/libmcrypt/modules/algorithms/3-way.c:14:
../lib/libmcrypt/lib/libdefs.h:49:11: fatal error: 'byteswap.h' file not found
# include <byteswap.h>
          ^
1 error generated.
make: *** [Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o] Error 1
```

**Comment by tugrul** [comment]
@jsolis can you configure & compile libmcrypt externally and send `config.h` file to me?

http://sourceforge.net/projects/mcrypt/files/Libmcrypt/2.5.8/

**Comment by jsolis** [comment]
Sure thing.  Definitely appreciate the effort here :+1: 

Pasted my config.h after running ./configure and  make on libcrypt
https://gist.github.com/jsolis/57702f4c5e2a487d828a

**Comment by tugrul** [comment]
@jsolis `mcrypt@0.1.8`

**Comment by jsolis** [comment]
:+1: :exclamation: I was able to successfully install and run my project using `mcrypt@0.1.8` on a mac using both `node@0.12.7` and `node@4.2.2`.  Thanks so much for your help on this @tugrul, I can't tell you how much we appreciate it.
