### ISSUE TITLE
ode v5.0.0Can't install mcrypt 0.0.7 on and npm  v3.3.12

### ISSUE THREAD

**Issue by sibok** [tugrul/node-mcrypt#43]
This is system installed libmcrypt version 2.5.8-r3

Install Log:
Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:547:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("validateKeySize"), FunctionTemplate::New(ValidateKeySize)->GetFunction());
                    ^
../src/mcrypt.cc:547:95: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("validateKeySize"), FunctionTemplate::New(ValidateKeySize)->GetFunction());
                                                                                               ^
../src/mcrypt.cc:547:95: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:548:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("validateIvSize"), FunctionTemplate::New(ValidateIvSize)->GetFunction());
                    ^
../src/mcrypt.cc:548:93: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("validateIvSize"), FunctionTemplate::New(ValidateIvSize)->GetFunction());
                                                                                             ^
../src/mcrypt.cc:548:93: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:549:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("selfTest"), FunctionTemplate::New(SelfTest)->GetFunction());
                    ^
../src/mcrypt.cc:549:81: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("selfTest"), FunctionTemplate::New(SelfTest)->GetFunction());
                                                                                 ^
../src/mcrypt.cc:549:81: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:550:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("isBlockAlgorithmMode"), FunctionTemplate::New(IsBlockAlgorithmMode)->GetFunction());
                    ^
../src/mcrypt.cc:550:105: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("isBlockAlgorithmMode"), FunctionTemplate::New(IsBlockAlgorithmMode)->GetFunction());
                                                                                                         ^
../src/mcrypt.cc:550:105: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:551:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("isBlockAlgorithm"), FunctionTemplate::New(IsBlockAlgorithm)->GetFunction());
                    ^
../src/mcrypt.cc:551:97: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("isBlockAlgorithm"), FunctionTemplate::New(IsBlockAlgorithm)->GetFunction());
                                                                                                 ^
../src/mcrypt.cc:551:97: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:552:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("isBlockMode"), FunctionTemplate::New(IsBlockMode)->GetFunction());
                    ^
../src/mcrypt.cc:552:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("isBlockMode"), FunctionTemplate::New(IsBlockMode)->GetFunction());
                                                                                       ^
../src/mcrypt.cc:552:87: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:553:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("getBlockSize"), FunctionTemplate::New(GetBlockSize)->GetFunction());
                    ^
../src/mcrypt.cc:553:89: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("getBlockSize"), FunctionTemplate::New(GetBlockSize)->GetFunction());
                                                                                         ^
../src/mcrypt.cc:553:89: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:554:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("getKeySize"), FunctionTemplate::New(GetKeySize)->GetFunction());
                    ^
../src/mcrypt.cc:554:85: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("getKeySize"), FunctionTemplate::New(GetKeySize)->GetFunction());
                                                                                     ^
../src/mcrypt.cc:554:85: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:555:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("getSupportedKeySizes"), FunctionTemplate::New(GetSupportedKeySizes)->GetFunction());
                    ^
../src/mcrypt.cc:555:105: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("getSupportedKeySizes"), FunctionTemplate::New(GetSupportedKeySizes)->GetFunction());
                                                                                                         ^
../src/mcrypt.cc:555:105: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:556:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("getIvSize"), FunctionTemplate::New(GetIvSize)->GetFunction());
                    ^
../src/mcrypt.cc:556:83: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("getIvSize"), FunctionTemplate::New(GetIvSize)->GetFunction());
                                                                                   ^
../src/mcrypt.cc:556:83: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:557:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("hasIv"), FunctionTemplate::New(HasIv)->GetFunction());
                    ^
../src/mcrypt.cc:557:75: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("hasIv"), FunctionTemplate::New(HasIv)->GetFunction());
                                                                           ^
../src/mcrypt.cc:557:75: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:558:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("getAlgorithmName"), FunctionTemplate::New(GetAlgorithmName)->GetFunction());
                    ^
../src/mcrypt.cc:558:97: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("getAlgorithmName"), FunctionTemplate::New(GetAlgorithmName)->GetFunction());
                                                                                                 ^
../src/mcrypt.cc:558:97: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:559:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("getModeName"), FunctionTemplate::New(GetModeName)->GetFunction());
                    ^
../src/mcrypt.cc:559:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("getModeName"), FunctionTemplate::New(GetModeName)->GetFunction());
                                                                                       ^
../src/mcrypt.cc:559:87: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:560:20: error: ‘NewSymbol’ is not a member of ‘v8::String’
     prototype->Set(String::NewSymbol("generateIv"), FunctionTemplate::New(GenerateIv)->GetFunction());
                    ^
../src/mcrypt.cc:560:85: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     prototype->Set(String::NewSymbol("generateIv"), FunctionTemplate::New(GenerateIv)->GetFunction());
                                                                                     ^
../src/mcrypt.cc:560:85: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:563:63: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Local<v8::Function>)’
     constructor = Persistent<Function>::New(tpl->GetFunction());
                                                               ^
../src/mcrypt.cc:563:63: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:7171:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:7171:4: note:   candidate expects 2 arguments, 1 provided
../src/mcrypt.cc:564:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("MCrypt"), constructor);
                  ^
../src/mcrypt.cc:565:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("getAlgorithmNames"), FunctionTemplate::New(GetAlgorithmNames)->GetFunction());
                  ^
../src/mcrypt.cc:565:97: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("getAlgorithmNames"), FunctionTemplate::New(GetAlgorithmNames)->GetFunction());
                                                                                                 ^
../src/mcrypt.cc:565:97: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc:566:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("getModeNames"), FunctionTemplate::New(GetModeNames)->GetFunction());
                  ^
../src/mcrypt.cc:566:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("getModeNames"), FunctionTemplate::New(GetModeNames)->GetFunction());
                                                                                       ^
../src/mcrypt.cc:566:87: note: candidate is:
In file included from /home/sibok/.node-gyp/5.0.0/include/node/node.h:42:0,
                 from ../src/mcrypt.cc:5:
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sibok/.node-gyp/5.0.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::New(const int&)’:
../src/mcrypt.cc:50:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::Encrypt(const int&)’:
../src/mcrypt.cc:118:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::Decrypt(const int&)’:
../src/mcrypt.cc:180:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::Open(const int&)’:
../src/mcrypt.cc:258:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::ValidateKeySize(const int&)’:
../src/mcrypt.cc:272:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::ValidateIvSize(const int&)’:
../src/mcrypt.cc:286:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::SelfTest(const int&)’:
../src/mcrypt.cc:302:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::IsBlockAlgorithmMode(const int&)’:
../src/mcrypt.cc:318:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::IsBlockAlgorithm(const int&)’:
../src/mcrypt.cc:334:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::IsBlockMode(const int&)’:
../src/mcrypt.cc:350:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GetBlockSize(const int&)’:
../src/mcrypt.cc:364:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GetKeySize(const int&)’:
../src/mcrypt.cc:378:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GetSupportedKeySizes(const int&)’:
../src/mcrypt.cc:405:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GetIvSize(const int&)’:
../src/mcrypt.cc:419:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::HasIv(const int&)’:
../src/mcrypt.cc:435:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GetAlgorithmName(const int&)’:
../src/mcrypt.cc:451:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GetModeName(const int&)’:
../src/mcrypt.cc:467:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GenerateIv(const int&)’:
../src/mcrypt.cc:489:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GetAlgorithmNames(const int&)’:
../src/mcrypt.cc:512:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/mcrypt.cc: In static member function ‘static v8::Handle<v8::Value> MCrypt::GetModeNames(const int&)’:
../src/mcrypt.cc:534:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
mcrypt.target.mk:92: recipe for target 'Release/obj.target/mcrypt/src/mcrypt.o' failed
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
make: Leaving directory '/home/sibok/public_html/bobbysf2/nodejs/node_modules/mcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.5-gentoo
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/sibok/public_html/bobbysf2/nodejs/node_modules/mcrypt
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.2.5-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.0.7 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.0.7 install script 'node-gyp rebuild --release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sibok/public_html/bobbysf2/nodejs/npm-debug.log

**Comment by tugrul** [comment]
`mcrypt@0.0.7` too old and `mcrypt@0.1.9` works fine with Node.js 5
