### ISSUE TITLE
Trouble With Rijndael-256 Implementation

### ISSUE THREAD

**Issue by siromivel** [tugrul/node-mcrypt#44]
I'm working on a project that requires me to decrypt a string ciphered with Rijndael-256 (256 block & key size,) and am having a hard time getting this module to work properly with this algorithm.

My current test code is:
```
var MCrypt = require('mcrypt').MCrypt;
 
var rj256 = new MCrypt('rijndael-256', 'cbc');
rj256.open('32charteststring32charteststring');
 
var ciphered = rj256.encrypt('super secret stuff.');
console.log(ciphered.toString('base64'));
 
var plaintext = rj256.decrypt(new Buffer(ciphered));
console.log(plaintext.toString());
```

Based on the examples I've seen in the docs both on GitHub and npm(https://www.npmjs.com/package/mcrypt) I believe that this code should be correctly returning the original string "super secret stuff." but it is outputting random(presumably still ciphered,) text instead.

I apologize if this is simply user error!

**Comment by tugrul** [comment]
Yes there is an error without IV but im able to get no error using IV.

This mode require to use IV and maybe the library should generate IV automatically if there was no provided IV.

https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Block_Chaining_.28CBC.29

**Comment by siromivel** [comment]
Thanks for that, don't know how I missed it! Everything is working perfectly now.
