### ISSUE TITLE
It is not installed on Windows

### ISSUE THREAD

**Issue by rpkim** [tugrul/node-mcrypt#46]
rypt\modules\algorithms\twofish.c) [D:\Project\aaaaa\server\node_modules\mc
rypt\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\algorithms\twofish.c(484): error C2054: expected
 '(' to follow 'inline' [D:\Project\aaaaa\server\node_modules\mcrypt\build\
lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\algorithms\wake.c) [D:\Project\aaaaa\server\node_modules\mcrypt\buil
d\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\algorithms\twofish.c(485): error C2085: 'f_rnd'
: not in formal parameter list [D:\Project\aaaaa\server\node_modules\mcrypt
\build\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\algorithms\xtea.c) [D:\Project\aaaaa\server\node_modules\mcrypt\buil
d\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\modes\cbc.c) [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\
libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\algorithms\wake.c) [D:\Project\aaaaa\server\node_modules\mcr
ypt\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\algorithms\twofish.c(485): error C2143: syntax e
rror : missing ';' before '{' [D:\Project\aaaaa\server\node_modules\mcrypt\
build\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\algorithms\xtea.c) [D:\Project\aaaaa\server\node_modules\mcr
ypt\build\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\modes\cbc.c) [D:\Project\aaaaa\server\node_modules\mcrypt\bu
ild\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\algorithms\wake.c) [D:\Project\aaaaa\server\node_modules\mcryp
t\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\algorithms\twofish.c(515): warning C4013: 'f_rnd
' undefined; assuming extern returning int [D:\Project\aaaaa\server\node_mo
dules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\algorithms\xtea.c) [D:\Project\aaaaa\server\node_modules\mcryp
t\build\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\modes\cbc.c) [D:\Project\aaaaa\server\node_modules\mcrypt\buil
d\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\algorithms\wake.c(141): error C2054: expected '(
' to follow 'inline' [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib
\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\algorithms\wake.c(142): error C2085: '_int_M' :
not in formal parameter list [D:\Project\aaaaa\server\node_modules\mcrypt\b
uild\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\algorithms\wake.c(142): error C2143: syntax erro
r : missing ';' before '{' [D:\Project\aaaaa\server\node_modules\mcrypt\bui
ld\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\algorithms\wake.c(189): warning C4013: '_int_M'
undefined; assuming extern returning int [D:\Project\aaaaa\server\node_modu
les\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
  cfb.c
  ctr.c
  ecb.c
  ncfb.c
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\modes\ctr.c) [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\
libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\modes\ctr.c) [D:\Project\aaaaa\server\node_modules\mcrypt\bu
ild\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\modes\cfb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\
libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\modes\ctr.c) [D:\Project\aaaaa\server\node_modules\mcrypt\buil
d\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\modes\cfb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\bu
ild\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\modes\cfb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\buil
d\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ctr.c(126): error C2054: expected '(' to f
ollow 'inline' [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\libmc
rypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ctr.c(127): error C2085: 'xor_stuff' : not
 in formal parameter list [D:\Project\aaaaa\server\node_modules\mcrypt\buil
d\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ctr.c(127): error C2143: syntax error : mi
ssing ';' before '{' [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib
\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ctr.c(204): warning C4013: 'xor_stuff' und
efined; assuming extern returning int [D:\Project\aaaaa\server\node_modules
\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\modes\ncfb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib
\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\modes\ecb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\
libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\modes\ncfb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\b
uild\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\modes\ecb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\bu
ild\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\modes\ncfb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\bui
ld\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\modes\ecb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\buil
d\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ncfb.c(105): error C2054: expected '(' to
follow 'inline' [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\libm
crypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ncfb.c(106): error C2085: 'xor_stuff_en' :
 not in formal parameter list [D:\Project\aaaaa\server\node_modules\mcrypt\
build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ncfb.c(106): error C2143: syntax error : m
issing ';' before '{' [D:\Project\aaaaa\server\node_modules\mcrypt\build\li
b\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ncfb.c(182): error C2054: expected '(' to
follow 'inline' [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\libm
crypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ncfb.c(183): error C2085: 'xor_stuff_de' :
 not in formal parameter list [D:\Project\aaaaa\server\node_modules\mcrypt\
build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ncfb.c(183): error C2143: syntax error : m
issing ';' before '{' [D:\Project\aaaaa\server\node_modules\mcrypt\build\li
b\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ncfb.c(271): warning C4013: 'xor_stuff_en'
 undefined; assuming extern returning int [D:\Project\aaaaa\server\node_mod
ules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\ncfb.c(293): warning C4013: 'xor_stuff_de'
 undefined; assuming extern returning int [D:\Project\aaaaa\server\node_mod
ules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
  nofb.c
  ofb.c
  stream.c
  bzero.c
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\modes\ofb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\
libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\modes\ofb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\bu
ild\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\modes\ofb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\buil
d\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\modes\nofb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib
\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\modes\nofb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\b
uild\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\modes\nofb.c) [D:\Project\aaaaa\server\node_modules\mcrypt\bui
ld\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\nofb.c(105): error C2054: expected '(' to
follow 'inline' [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\libm
crypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\nofb.c(106): error C2085: 'xor_stuff' : no
t in formal parameter list [D:\Project\aaaaa\server\node_modules\mcrypt\bui
ld\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(36): error C2054: expected '(' to follow 'inline' (......\lib\libmcrypt\m
odules\modes\stream.c) [D:\Project\aaaaa\server\node_modules\mcrypt\build\l
ib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\nofb.c(106): error C2143: syntax error : m
issing ';' before '{' [D:\Project\aaaaa\server\node_modules\mcrypt\build\li
b\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2085: 'memxor' : not in formal parameter list (......\lib\lib
mcrypt\modules\modes\stream.c) [D:\Project\aaaaa\server\node_modules\mcrypt
\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\modules\modes\nofb.c(189): warning C4013: 'xor_stuff' un
defined; assuming extern returning int [D:\Project\aaaaa\server\node_module
s\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
D:\Project\aaaaa\server\node_modules\mcrypt\lib\libmcrypt\lib\mcrypt_module
s.h(37): error C2143: syntax error : missing ';' before '{' (......\lib\libmc
rypt\modules\modes\stream.c) [D:\Project\aaaaa\server\node_modules\mcrypt\b
uild\lib\libmcrypt\libmcrypt.vcxproj]
  mcrypt.c
  mcrypt_extra.c
  mcrypt_modules.c
  mcrypt_symb.c
......\lib\libmcrypt\lib\mcrypt_symb.c(461): warning C4113: 'int (__cdecl *)(
)' differs in parameter lists from 'int (__cdecl *)(void *,const void *,int,con
st void *,int)' [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\libm
crypt\libmcrypt.vcxproj]
......\lib\libmcrypt\lib\mcrypt_symb.c(461): warning C4113: 'int (__cdecl *)(
)' differs in parameter lists from 'int (__cdecl *)(void *,const void *,int)' [
D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.v
cxproj]
......\lib\libmcrypt\lib\mcrypt_symb.c(461): warning C4113: 'int (__cdecl *)(
)' differs in parameter lists from 'int (__cdecl *)(void *,void *,int *)' [D:\P
roject\aaaaa\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxpr
oj]
......\lib\libmcrypt\lib\mcrypt_symb.c(461): warning C4113: 'int (__cdecl *)(
)' differs in parameter lists from 'int (__cdecl *)(void *)' [D:\Project\FlyMan
ana\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\lib\mcrypt_symb.c(461): warning C4113: 'int (__cdecl *)(
)' differs in parameter lists from 'int (__cdecl *)(void *,void *,int,int,void
*,void *,void *)' [D:\Project\aaaaa\server\node_modules\mcrypt\build\lib\li
bmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\lib\mcrypt_symb.c(461): warning C4113: 'int (__cdecl *)(
)' differs in parameter lists from 'int (__cdecl *)(void)' [D:\Project\FlyManan
a\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\lib\mcrypt_symb.c(461): warning C4113: 'char *(__cdecl *
)()' differs in parameter lists from 'char *(__cdecl *)(void)' [D:\Project\FlyM
anana\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\lib\mcrypt_symb.c(461): warning C4113: 'word32 (__cdecl
*)()' differs in parameter lists from 'word32 (__cdecl *)(void)' [D:\Project\Fl
yManana\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\lib\mcrypt_symb.c(734): warning C4113: 'int (__cdecl *)(
)' differs in parameter lists from 'int (__cdecl *)(void)' [D:\Project\FlyManan
a\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
......\lib\libmcrypt\lib\mcrypt_symb.c(734): warning C4113: 'const int *(__cd
ecl *)()' differs in parameter lists from 'const int *(__cdecl *)(int *)' [D:\P
roject\aaaaa\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxpr
oj]
......\lib\libmcrypt\lib\mcrypt_symb.c(734): warning C4113: 'const char *(__c
decl *)()' differs in parameter lists from 'const char *(__cdecl *)(void)' [D:\
Project\aaaaa\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxp
roj]
......\lib\libmcrypt\lib\mcrypt_symb.c(734): warning C4113: 'word32 (__cdecl
*)()' differs in parameter lists from 'word32 (__cdecl *)(void)' [D:\Project\Fl
yManana\server\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
  xmemory.c
  win_delay_load_hook.c
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Jay\AppData\Roaming\npm\node
_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Jay\AppData\
\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "reb
uild" "--release"
gyp ERR! cwd D:\Project\aaaaa\server\node_modules\mcrypt
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
install → rollbackFailedO ▄ ╢██████████████████████████████████████████░░░░░░░╟
install → rollbackFailedO ▌ ╢██████████████████████████████████████████░░░░░░░╟
aaaaa_Server_DEV@0.0.0 D:\Project\aaaaa\server
├── bcrypt@0.8.5  extraneous
└── node-cryptojs-aes@0.4.0  extraneous

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Jay\AppData\Ro
aming\npm\node_modules\npm\bin\npm-cli.js" "install" "mcrypt"
npm ERR! node v5.1.1
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.9 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mcrypt@0.1.9 install script 'node-gyp rebuild --release'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Project\aaaaa\server\npm-debug.log

D:\Project\aaaaa\server>

**Comment by tugrul** [comment]
What is version of your Visual C++ compiler?

**Comment by rpkim** [comment]
My version is 2010

2016년 1월 10일 (일) 20:54, Tuğrul Topuz <notifications@github.com>님이 작성:

**Comment by tugrul** [comment]
Probably your c++ compiler is not compatible with c++11 features. https://msdn.microsoft.com/en-us/library/hh567368.aspx

https://github.com/nodejs/node-gyp

**Comment by rpkim** [comment]
Thanks. I try again with c++ 11

2016년 1월 11일 (월) 17:26, Tuğrul Topuz <notifications@github.com>님이 작성:
