### ISSUE TITLE
Failed at the mcrypt@0.1.12 install script 'node-gyp rebuild --release'.

### ISSUE THREAD

**Issue by tajhulfaijin** [tugrul/node-mcrypt#63]
Just installing mcrypt on my mac, and got this error : 

⇒  npm install mcrypt --save

> mcrypt@0.1.12 install /Users/mrjoule/Sites/.../node_modules/mcrypt
> node-gyp rebuild --release

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/mrjoule/Sites/.../node_modules/mcrypt
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mcrypt" "--save"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.12 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.1.12 install script 'node-gyp rebuild --release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

**Comment by tugrul** [comment]
`gyp ERR! stack Error: self signed certificate in certificate chain`

Please check your root ca certificates.
