### ISSUE TITLE
generateIv always return the same buffer

### ISSUE THREAD

**Issue by Extarys** [tugrul/node-mcrypt#68]
```
var enc = new MCrypt('twofish', 'cbc');
var iv = enc.generateIv()
```

`<Buffer d6 64 c7 cb e8 32 55 c3 46 8d 79 a0 5d 82 f2 e9>`
I assume that this is not the expected behavior? :\

**Comment by tugrul** [comment]
This method not uses a real psueido-random generator. It just use `std::rand()` function of c++.

You can use `crypto.randomBytes(size[, callback])` to get better variations.

https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback
