### ISSUE TITLE
Unable to build on Windows 10 x64

### ISSUE THREAD

**Issue by arkanos** [tugrul/node-mcrypt#69]
`Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 12.00.8168 for 80x86
  Copyright (C) Microsoft Corp 1984-1998. All rights reserved.

  cl  ■/

     \

     \

CL : Command line warning D4024: unrecognized source file type ' ■/', object file assumed [C:\Users\ruben.deig\Desktop\test\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
CL : Command line warning D4024: unrecognized source file type '\', object file assumed [C:\Users\ruben.deig\Desktop\test\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
CL : Command line warning D4024: unrecognized source file type '\', object file assumed [C:\Users\ruben.deig\Desktop\test\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
  Microsoft (R) Incremental Linker Version 6.00.8168
  Copyright (C) Microsoft Corp 1992-1998. All rights reserved.

  /out:.exe
   ■/
  \
  \
LINK : fatal error LNK1181: cannot open input file " ■/.obj" [C:\Users\ruben.deig\Desktop\test\node_modules\mcrypt\build\lib\libmcrypt\libmcrypt.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ruben.deig\Desktop\test\node_modules\mcrypt
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok`

C++ Redistributable 2010 to 2017 x86 and x64 are installed.

**Comment by tugrul** [comment]
It looks like locale specific problem.
