### ISSUE TITLE
Unable to install in windows

### ISSUE THREAD

**Issue by joweste** [tugrul/node-mcrypt#73]
Hi, I am unable to install in windows  8.1, node v8.11.3
Error log:

C:\nodeapp\newhospKeys\node_modules\mcrypt>if not defined npm_config_node_gyp (n
ode "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gy
p-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Pr
ogram Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebui
ld )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\nodeapp\newhospKeys\node_modules\mcrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN fb_acesso_remoto@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mcrypt@0.1.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mcrypt@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Luiz\AppData\Roaming\npm-cache\_logs\2018-07-07T15_49_48_1
75Z-debug.log

**Comment by tugrul** [comment]
`gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`

Your environment is incomplete. You have to install python and ms build tools.

https://github.com/nodejs/node-gyp#on-windows
