### ISSUE TITLE
MCrypt module could not open on AWS Lambda

### ISSUE THREAD

**Issue by martinbean** [tugrul/node-mcrypt#77]
I’m trying to use this package to create a simple Lambda function on AWS that decrypts a given ciphertext with a given string.

This is the entirety of my function:

```js
const MCrypt = require('mcrypt').MCrypt;
const mcrypt = new MCrypt('tripledes', 'esc');

exports.handler = async (event) => {
    mcrypt.open(event.key);

    const ciphertext = new Buffer(event.data, 'base64');
    const plaintext = mcrypt.decrypt(ciphertext);

    return plaintext.toString();
};
```

I installed the `mcrypt` package, zipped my **index.js** script and **node_modules** folder, and uploaded it to Lambda. When I try to execute the function, it fails with this error:

```json
{
  "errorMessage": "MCrypt module could not open",
  "errorType": "Error",
  "stackTrace": [
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)"
  ]
}
```

The function _does_ work in a Vagrant box. Why does it not work under Lambda?

**Comment by tugrul** [comment]
```javascript
const mcrypt = new MCrypt('tripledes', 'esc');
```

MCrypt not contains **esc** mode.

You can check it by calling `getModeNames()` function.

https://github.com/tugrul/node-mcrypt#getmodenames--array

**Comment by martinbean** [comment]
@tugrul So why does it work locally?

**Comment by joebowbeer** [comment]
The binding.gyp will pose a problem for Lambda. Search for articles such as [How to Run Native Addon Modules for Node.js in AWS Lambda](https://blog.usejournal.com/how-to-run-native-addon-modules-for-node-js-in-aws-lambda-aa74e1a9010).
