### ISSUE TITLE
Keeps crashing on CentOS

### ISSUE THREAD

**Issue by majimboo** [tugrul/node-mcrypt#8]
It just keeps crashing on centOS. when on the line to `decrypt`. Could it be a missing library? I only installed `libmcrypt-devel`, can't find `libmcrypt4` in centos.

**Comment by William-Yeh** [comment]
@ewein
I have an example without segmentation fault on CentOS 6.6:
https://gist.github.com/William-Yeh/caa3b1acbbc91f5a308b
