### ISSUE TITLE
Problem to using the types version in angular 5

### ISSUE THREAD

**Issue by jevilla94** [tugrul/node-mcrypt#80]
Hello
I am using the package @types/mcrypt on a project with a ngx-admin template; built component is:

import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { TranslateService, LangChangeEvent } from '@ngx-translate/core';
import { getAlgorithmNames, getModeNames, MCrypt } from "mcrypt";

@component({
selector: 'ngx-recibo',
templateUrl: './recibo.component.html',
styleUrls: ['./recibo.component.scss'],
})
export class ReciboComponent implements OnInit {
algos: string[];
constructor(private translate: TranslateService) {
this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
});
}
public send() {
algos = getModeNames();
console.info(this.algos);
}
useLanguage(language: string) {
this.translate.use(language);
}
ngOnInit() {
}
}

However, when I execute my project, this error is generated:

    ERROR in ./node_modules/bindings/bindings.js
    Module not found: Error: Can't resolve 'fs' in '/home/planestic/campus_cliente/node_modules/bindings'
    ERROR in ./node_modules/bindings/bindings.js
    Module not found: Error: Can't resolve 'path' in '/home/planestic/campus_cliente/node_modules/bindings'
    ERROR in ./node_modules/file-uri-to-path/index.js
    Module not found: Error: Can't resolve 'path' in '/home/planestic/campus_cliente/node_modules/file-uri-to-path'

And these libraries are installed; please, I thank your help

**Comment by tugrul** [comment]
This library is not isomorphic and you can only use on server-side.
