### ISSUE TITLE
when i run i get error: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ronovar** [tugrul/node-mcrypt#81]
Hi, when i run node-mcrypt on PC it runs OK and works. So i switched to arm arhictecture armv7 and need tutorial how to cross compile it to run on armv7 archictecture so if you could give me web site or write short tutorial how to cross compile node-mcrypt for arm?

I searched internet but i did not find detail instructions how to do that.

Thanks

**Comment by tugrul** [comment]
do you have compiler toolchain on arm device?

I tested before it had worked on raspberry pi.

**Comment by ronovar** [comment]
I have NanoPI Neo2 with 1GB of RAM

http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO2

How can i check if i have toolchain on arm device? I im new to toolchain so if you please could guide me how to compile for arm or any web site that have nice tutorial how to do it.

**Comment by tugrul** [comment]
This issue is not subject of project. You can just use google to find. 

You can install `sudo apt-get install build-essential` if your Nano PI OS is debian based. https://askubuntu.com/questions/398489/how-to-install-build-essential
