### ISSUE TITLE
Use Pkcs7 or other padding.

### ISSUE THREAD

**Issue by dirname** [tugrul/node-mcrypt#82]
I want to use pkcs7 in my __Twofish__ encryption. But there's no way to set it up to be inappropriate for zeros padding. I try to apply __cryptian__. It's not supported __Twofish__.Hope to get your help.

Thank you.

**Comment by tugrul** [comment]
I'm going to try to port **twofish** inside **cryptian** library in free time. 

In this time you can use encryption algorithm from **node-mcrypt** and padding algorithm from **cryptian**. 

Padding algorithms of **cryptian** are flexible to use standalone.

Thanks

**Comment by dirname** [comment]
I just use mcrypt to solved my problem.Padding in before encryption. When the length equals the length of the block, it will not automatically zeros padding.

Thank you again for your efforts.
