### ISSUE TITLE
Cannot use mcrypt with node 12.14.0 latest LTS.

### ISSUE THREAD

**Issue by SSANSH** [tugrul/node-mcrypt#84]
logs produce by npm i

`./src/mcrypt.cc: At global scope:
../src/mcrypt.cc:503:19: error: variable or field ‘Init’ declared void
  503 | void MCrypt::Init(Handle<Object> exports) {
      |                   ^~~~~~
../src/mcrypt.cc:503:19: error: ‘Handle’ was not declared in this scope
../src/mcrypt.cc:503:32: error: expected primary-expression before ‘>’ token
  503 | void MCrypt::Init(Handle<Object> exports) {
      |                                ^
../src/mcrypt.cc:503:34: error: ‘exports’ was not declared in this scope
  503 | void MCrypt::Init(Handle<Object> exports) {
      |                                  ^~~~~~~
In file included from ../../nan/nan.h:54,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
`

**Comment by tugrul** [comment]
I published a version to npm but I offer you to use cryptian package
